# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Google Play Console CLI"
  homepage "https://github.com/leszko11/google-play-console-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.3.0/gpc_v0.3.0_darwin_amd64.tar.gz"
      sha256 "e6b2b0bd417cc59b67d0a8e5cca33fd70ea65b3e49d5e2de935ba146d1ade9aa"

      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.3.0/gpc_v0.3.0_darwin_arm64.tar.gz"
      sha256 "0f75a1e215f624230b4c6971da6a2a280f653a4783950602abb0dadbf6040709"

      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.3.0/gpc_v0.3.0_linux_amd64.tar.gz"
      sha256 "16d6fddad5c482b1c91fc5b857146b4d8a9574ad61437b1fef4a625b34b98f82"
      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.3.0/gpc_v0.3.0_linux_arm64.tar.gz"
      sha256 "ba00500f00efadb9c5759484bb50b4e7220339922fd7a448b5d7ea39bedef973"
      define_method(:install) do
        bin.install "gpc"
      end
    end
  end
end
