# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpc < Formula
  desc "Google Play Console CLI"
  homepage "https://github.com/leszko11/google-play-console-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.4.0/gpc_v0.4.0_darwin_amd64.tar.gz"
      sha256 "89286cce0b7ccaab31bfb1e5bb6135aa68078cdaf17a3854982a8f38e1534147"

      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.4.0/gpc_v0.4.0_darwin_arm64.tar.gz"
      sha256 "857ad926769c3f208c04c845b4fe2d32908420ee2ae403ce6bc0079429f3524b"

      define_method(:install) do
        bin.install "gpc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.4.0/gpc_v0.4.0_linux_amd64.tar.gz"
      sha256 "2df27fdc9e34951b25b870a284d3eee01c2f5e03a17bb9ce735595676a1f5647"
      define_method(:install) do
        bin.install "gpc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leszko11/google-play-console-cli/releases/download/v0.4.0/gpc_v0.4.0_linux_arm64.tar.gz"
      sha256 "87342d875fa2695597cc3e5760a20157215266e3a5209f4d88617aa1e564d33b"
      define_method(:install) do
        bin.install "gpc"
      end
    end
  end
end
